version: '3.4'

services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - .\dashboards:/var/lib/grafana/dashboards
      - .\grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - .\grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      
  k6:
    container_name: k6
    image: grafana/k6:0.49.0
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./scripts:/scripts
    depends_on:
      - influxdb  
      
networks:
  k6:
  grafana:
  